<?php

namespace Tests\Feature;

use App\SioriFriends\Models\User\User;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class BookCreateTest extends TestCase
{
    use DatabaseTransactions;

    /** @var User */
    private $user;

    /** @var array */
    private $requestParameter;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::first();

        $this->requestParameter = [
            'title' => 'book title',
            'description' => 'この本の説明',
            'isPublishing' => true,
            'isCommentable' => false,
            'tags' => ['php', 'laravel'],
            'anchors' => [
                ['url' => 'http://qiita.com', 'name' => 'qiita'],
                ['url' => 'https://www.google.co.jp', 'name' => 'google'],
            ],
        ];
    }

    public function testPost()
    {
        Auth::login($this->user);
        $response = $this->post('/books', $this->requestParameter);

        $response->assertStatus(200);
    }
}
