<?php

namespace Tests\Unit;

use App\Siorifriends\Models\User\Follow;
use App\Siorifriends\Models\User\User;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class EloquentUserTest extends TestCase
{
//    use DatabaseMigrations;
    use DatabaseTransactions;

    /** @var User */
    private $target;
    /** @var User */
    private $user;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->target = factory(User::class)->create();
        $this->user   = factory(User::class)->create();
    }

    /**
     * ユーザをフォローできるか
     */
    public function testFollowFor()
    {
        $this->target->followFor($this->user->id);

        $this->assertDatabaseHas('follows', [
            'user_id'   => $this->target->id,
            'follow_id' => $this->user->id,
        ]);
    }

    public function testUnFollowFor()
    {
        $this->testFollowFor();
        $this->target->unFollowFor($this->user->id);

        $this->assertDatabaseMissing('follows', [
            'user_id'   => $this->target->id,
            'follow_id' => $this->user->id,
        ]);
    }

    public function testIsFollow()
    {
        $this->target->followFor($this->user->id);
        $this->assertTrue($this->target->isFollow($this->user->id));
        $this->target->unFollowFor($this->user->id);
        $this->assertFalse($this->target->isFollow($this->user->id));
    }
}
