<?php

namespace Tests\Unit;

use App\SioriFriends\Models\Book\Anchor;
use App\SioriFriends\Models\Book\Book;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class EloquentBookTest extends TestCase
{
    //    use DatabaseMigrations;
    use DatabaseTransactions;

    /** @var Book */
    private $target;

    private $anchor;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->target = factory(Book::class)->create();
        $this->anchor = factory(Anchor::class)->create();
    }

    public function testAddAnchor()
    {
        $this->target->addAnchor($this->anchor);

        $this->assertDatabaseHas('anchor_book', [
            'anchor_id' => $this->anchor->id,
            'book_id' => $this->target->id,
        ]);
    }

    public function testRemoveAnchor()
    {
        $this->testAddAnchor();
        $this->target->removeAnchor($this->anchor);

        $this->assertDatabaseMissing('anchor_book', [
            'anchor_id' => $this->anchor->id,
            'book_id' => $this->target->id,
        ]);
    }
}
